name: Integration tests - ERIGON

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main 
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  schedule:
    - cron: '20 16 * * *' # daily at 16:20 UTC
  workflow_dispatch:

jobs:
  source-of-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.filter.outputs.changed_files }}
    steps:
      - name: Check for changes outside specific directories
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            changed_files:
              - 'dashboards/**'
              - '**/.github/workflows/**'

  tests-mac-linux:
    needs: source-of-changes
    if: needs.source-of-changes.outputs.changed_files != 'true'
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-14
          - ubuntu-latest-erigontests-large
    runs-on: ${{ matrix.os }}

    steps:
      - name: Declare runners
        run: |
          set +x
          echo "I am being served by this runner: $RUNNER_NAME"
          
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Update submodules
        run: git submodule update --init --recursive --force
        
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: ${{ contains(fromJSON('["refs/heads/main","refs/heads/release/2.60","refs/heads/release/2.61"]'), github.ref) }}
          
      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install build-essential
        
      - name: Run integration tests on ${{ matrix.os }}
        run: GOGC=80 make test-integration

  tests-windows:
    needs: source-of-changes
    if: needs.source-of-changes.outputs.changed_files != 'true'
    strategy:
      matrix:
        os: [ windows-2022 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code on ${{ matrix.os }}
        uses: actions/checkout@v4
        
      - name: Update submodules on Windows
        run: git submodule update --init --recursive --force
        
      - name: Setup Go environment on ${{ matrix.os }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Cache Chocolatey packages
        uses: actions/cache@v4
        with:
          path: |
            C:\ProgramData\chocolatey\lib\mingw
            C:\ProgramData\chocolatey\lib\cmake
          key: chocolatey-${{ matrix.os }}
          
      - name: Install dependencies on ${{ matrix.os }}
        run: |
          choco upgrade mingw -y --no-progress --version 13.2.0

      - name: Run integration tests on ${{ matrix.os }}
        run: .\wmake.ps1 test-integration

  dummyOK:
    needs: source-of-changes
    if: needs.source-of-changes.outputs.changed_files == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: OK for the to-be-excluded directories
        run: echo "OK"
